# Generated by Django 4.2.6 on 2023-11-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(upload_to='images/', verbose_name='Логотип команды'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(upload_to='images/', verbose_name='Логотип турнира'),
        ),
    ]
