# Generated by Django 4.2.6 on 2023-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_player_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.TextField(default='Беларусь', verbose_name='Национальность'),
        ),
    ]
