# Generated by Django 4.2.6 on 2023-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_player_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Беларусь', max_length=20, verbose_name='Национальность'),
        ),
    ]
